<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Buddy Galletti">
<meta name="dcterms.date" content="2025-06-04">
<meta name="description" content="PP% and PK% are the most widely cited special teams metrics in hockey. They are also among the most misleading. Here’s a ground-up replacement.">

<title>Special Teams Rating: A Better Framework – Corsi Isn’t Enough</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-ccafe2c99a4564d55934ca8539ca9f46.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-67899a0544166b2f85d65ce54e7f18ed.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-B7SGED13J4"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-B7SGED13J4', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Corsi Isn’t Enough</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts/"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/corsi-isnt-enough/nhl-analytics"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://corsiistenough.substack.com"> <i class="bi bi-substack" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-problem-with-pp-and-pk" id="toc-the-problem-with-pp-and-pk" class="nav-link active" data-scroll-target="#the-problem-with-pp-and-pk">The Problem with PP% and PK%</a></li>
  <li><a href="#the-framework" id="toc-the-framework" class="nav-link" data-scroll-target="#the-framework">The Framework</a>
  <ul class="collapse">
  <li><a href="#per-60-normalization" id="toc-per-60-normalization" class="nav-link" data-scroll-target="#per-60-normalization">Per-60 Normalization</a></li>
  <li><a href="#score-state-stratification" id="toc-score-state-stratification" class="nav-link" data-scroll-target="#score-state-stratification">Score-State Stratification</a></li>
  <li><a href="#composite-str" id="toc-composite-str" class="nav-link" data-scroll-target="#composite-str">Composite STR</a></li>
  </ul></li>
  <li><a href="#the-data-pipeline" id="toc-the-data-pipeline" class="nav-link" data-scroll-target="#the-data-pipeline">The Data Pipeline</a></li>
  <li><a href="#results-score-state-is-not-uniform" id="toc-results-score-state-is-not-uniform" class="nav-link" data-scroll-target="#results-score-state-is-not-uniform">Results: Score State Is Not Uniform</a></li>
  <li><a href="#results-the-str-rankings" id="toc-results-the-str-rankings" class="nav-link" data-scroll-target="#results-the-str-rankings">Results: The STR Rankings</a></li>
  <li><a href="#results-pp-vs-pk-efficiency" id="toc-results-pp-vs-pk-efficiency" class="nav-link" data-scroll-target="#results-pp-vs-pk-efficiency">Results: PP vs PK Efficiency</a></li>
  <li><a href="#deep-dive-winnipeg-jets" id="toc-deep-dive-winnipeg-jets" class="nav-link" data-scroll-target="#deep-dive-winnipeg-jets">Deep Dive: Winnipeg Jets</a></li>
  <li><a href="#limitations-and-next-steps" id="toc-limitations-and-next-steps" class="nav-link" data-scroll-target="#limitations-and-next-steps">Limitations and Next Steps</a></li>
  <li><a href="#full-code" id="toc-full-code" class="nav-link" data-scroll-target="#full-code">Full Code</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Special Teams Rating: A Better Framework</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">special-teams</div>
    <div class="quarto-category">methodology</div>
    <div class="quarto-category">power-play</div>
    <div class="quarto-category">penalty-kill</div>
  </div>
  </div>

<div>
  <div class="description">
    PP% and PK% are the most widely cited special teams metrics in hockey. They are also among the most misleading. Here’s a ground-up replacement.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Buddy Galletti </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 4, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-problem-with-pp-and-pk" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-with-pp-and-pk">The Problem with PP% and PK%</h2>
<p>Ask anyone to evaluate a team’s special teams and the first thing they reach for is PP% and PK%. Power play percentage: goals scored divided by opportunities. Penalty kill percentage: opportunities killed without conceding. Simple, intuitive, universally reported.</p>
<p>Also quietly broken.</p>
<p>Here’s the core issue: <strong>both metrics treat all special teams time as equivalent</strong>, when it clearly isn’t. A two-minute power play when you’re down three goals in the third period is a completely different situation — in terms of strategy, urgency, and opponent behavior — than a power play when you’re protecting a one-goal lead in the second. Teams change how they play. Goaltenders change how they play. The underlying rates of scoring chance generation shift meaningfully across these contexts.</p>
<p>When you collapse all of that into a single percentage, you’re averaging over a distribution that shouldn’t be averaged. You’re measuring outcomes, not quality. And you’re throwing away some of the most useful signal in the data.</p>
<p>There’s a second problem: <strong>opportunity count as the denominator is unstable</strong>. A team that takes 10 power plays in a sample scores on 2 of them: 20%. A team that takes 40 power plays scores on 8: also 20%. These are treated as equivalent, but the second estimate is far more reliable. Per-60 metrics, where time-on-ice is the denominator, normalize this properly.</p>
<p>This post introduces <strong>Special Teams Rating (STR)</strong> — a framework built from play-by-play data that replaces both problems with something more honest.</p>
<hr>
</section>
<section id="the-framework" class="level2">
<h2 class="anchored" data-anchor-id="the-framework">The Framework</h2>
<p>STR has three components that build on each other:</p>
<ol type="1">
<li><strong>Per-60 normalization</strong> — replace opportunity counts with time-on-ice as the denominator</li>
<li><strong>Score-state stratification</strong> — split all special teams events into five game-context buckets</li>
<li><strong>Composite z-score rating</strong> — combine PP and PK components into a single team ranking</li>
</ol>
<section id="per-60-normalization" class="level3">
<h3 class="anchored" data-anchor-id="per-60-normalization">Per-60 Normalization</h3>
<p>For any team <span class="math inline">\(t\)</span> in any score-state bucket <span class="math inline">\(b\)</span>, define:</p>
<p><span class="math display">\[
\text{PP Goals/60}_{t,b} = \frac{\text{PP Goals}_{t,b}}{\text{PP TOI}_{t,b}} \times 60
\]</span></p>
<p><span class="math display">\[
\text{PK GA/60}_{t,b} = \frac{\text{PK Goals Against}_{t,b}}{\text{PK TOI}_{t,b}} \times 60
\]</span></p>
<p>Where TOI is measured in minutes from the raw play-by-play. This immediately solves the sample-size distortion: a team with 3 minutes of power play time in a given bucket simply has a noisier estimate, not an artificially inflated or deflated percentage.</p>
<p>We also track shot attempt volume as a process quality measure:</p>
<p><span class="math display">\[
\text{PP Attempts/60}_{t,b} = \frac{\text{SOG} + \text{Missed} + \text{Blocked}}{\text{PP TOI}_{t,b}} \times 60
\]</span></p>
</section>
<section id="score-state-stratification" class="level3">
<h3 class="anchored" data-anchor-id="score-state-stratification">Score-State Stratification</h3>
<p>Every penalty in the data is classified at the moment it is called. The goal differential from the power play team’s perspective determines the bucket:</p>
<p><span class="math display">\[
\Delta g = \text{Goals}_{PP\text{ team}} - \text{Goals}_{PK\text{ team}} \quad \text{at time of penalty}
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bucket</th>
<th>Condition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Chasing</td>
<td><span class="math inline">\(\Delta g \leq -2\)</span></td>
</tr>
<tr class="even">
<td>Trailing</td>
<td><span class="math inline">\(\Delta g = -1\)</span></td>
</tr>
<tr class="odd">
<td>Neutral</td>
<td><span class="math inline">\(\Delta g = 0\)</span></td>
</tr>
<tr class="even">
<td>Leading</td>
<td><span class="math inline">\(\Delta g = +1\)</span></td>
</tr>
<tr class="odd">
<td>Protecting</td>
<td><span class="math inline">\(\Delta g \geq +2\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="composite-str" class="level3">
<h3 class="anchored" data-anchor-id="composite-str">Composite STR</h3>
<p>To combine PP and PK performance into a single number, we z-score each component across the league, then apply a weighted sum:</p>
<p><span class="math display">\[
z_x = \frac{x - \bar{x}}{\sigma_x}
\]</span></p>
<p><span class="math display">\[
\text{STR}_t = 0.40 \cdot z_{\text{PP Goals/60}} + 0.10 \cdot z_{\text{PP Attempts/60}} - 0.40 \cdot z_{\text{PK GA/60}} - 0.10 \cdot z_{\text{PK Shots Against/60}}
\]</span></p>
<p>The weights reflect a deliberate philosophy:</p>
<ul>
<li><strong>Goals/60 (40% each side)</strong> — outcomes are the primary signal</li>
<li><strong>Shot attempts/60 (10% each side)</strong> — process quality is a secondary signal; volume matters but doesn’t dominate</li>
<li><strong>PK components are inverted</strong> — lower goals against and fewer shots against are better, so the z-scores are negated before weighting</li>
</ul>
<p>The result is a league-relative rating where positive values mean above average and negative values mean below average.</p>
<hr>
</section>
</section>
<section id="the-data-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="the-data-pipeline">The Data Pipeline</h2>
<p>Everything runs off the NHL public API’s play-by-play endpoint:</p>
<pre><code>GET https://api-web.nhle.com/v1/gamecenter/{game_id}/play-by-play</code></pre>
<p>For each game, we make three passes through the event stream:</p>
<p><strong>Pass 1 — Score reconstruction.</strong> Walk every event in chronological order, maintaining a live running score for both teams. This is necessary because the API does not store cumulative score on non-goal events — we have to reconstruct it ourselves.</p>
<p><strong>Pass 2 — Penalty window identification.</strong> For each <code>penalty</code> event, record the PP team, PK team, start time, nominal duration, and the score state at the moment the penalty was called (from Pass 1’s running tally).</p>
<p><strong>Pass 3 — Event tagging.</strong> For each penalty window, collect all shot-type events (<code>shot-on-goal</code>, <code>goal</code>, <code>missed-shot</code>, <code>blocked-shot</code>) that fall within the window’s time range, attributed to the correct team. One important detail: a power play goal ends a minor penalty early, so we detect that and clip the window’s actual end time accordingly.</p>
<div id="dependencies" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm.notebook <span class="im">import</span> tqdm</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.ticker <span class="im">as</span> mticker</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.max_columns'</span>, <span class="va">None</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.float_format'</span>, <span class="st">'</span><span class="sc">{:.3f}</span><span class="st">'</span>.<span class="bu">format</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>BASE_URL <span class="op">=</span> <span class="st">'https://api-web.nhle.com/v1'</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Libraries loaded.'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="config" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>SEASON        <span class="op">=</span> <span class="st">'20242025'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>GAME_TYPE     <span class="op">=</span> <span class="dv">2</span>          <span class="co"># 2 = regular season, 3 = playoffs</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>MAX_GAMES     <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>SLEEP_BETWEEN_REQUESTS <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score_state_bucket(goal_diff: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>   goal_diff <span class="op">&lt;=</span>  <span class="op">-</span><span class="dv">2</span>: <span class="cf">return</span> <span class="st">'Chasing'</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> goal_diff <span class="op">==</span>  <span class="op">-</span><span class="dv">1</span>: <span class="cf">return</span> <span class="st">'Trailing'</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> goal_diff <span class="op">==</span>   <span class="dv">0</span>: <span class="cf">return</span> <span class="st">'Neutral'</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> goal_diff <span class="op">==</span>   <span class="dv">1</span>: <span class="cf">return</span> <span class="st">'Leading'</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:                  <span class="cf">return</span> <span class="st">'Protecting'</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>BUCKET_ORDER <span class="op">=</span> [<span class="st">'Chasing'</span>, <span class="st">'Trailing'</span>, <span class="st">'Neutral'</span>, <span class="st">'Leading'</span>, <span class="st">'Protecting'</span>]</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Config: season=</span><span class="sc">{</span>SEASON<span class="sc">}</span><span class="ss">, game_type=</span><span class="sc">{</span>GAME_TYPE<span class="sc">}</span><span class="ss">, max_games=</span><span class="sc">{</span>MAX_GAMES<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="fetch-game-ids" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_game_ids(season: <span class="bu">str</span>, game_type: <span class="bu">int</span>, max_games<span class="op">=</span><span class="va">None</span>) <span class="op">-&gt;</span> <span class="bu">list</span>:</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Pull all completed regular-season game IDs via the schedule endpoint."""</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    url <span class="op">=</span> <span class="ss">f'</span><span class="sc">{</span>BASE_URL<span class="sc">}</span><span class="ss">/schedule/season/</span><span class="sc">{</span>season<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>game_type<span class="sc">}</span><span class="ss">'</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    resp <span class="op">=</span> requests.get(url)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> resp.status_code <span class="op">!=</span> <span class="dv">200</span>:</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'Schedule endpoint returned </span><span class="sc">{</span>resp<span class="sc">.</span>status_code<span class="sc">}</span><span class="ss">, falling back to date-range walk.'</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> _walk_schedule_by_date(season, game_type, max_games)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> resp.json()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    game_ids <span class="op">=</span> []</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> week <span class="kw">in</span> data.get(<span class="st">'gameWeek'</span>, []):</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> game <span class="kw">in</span> week.get(<span class="st">'games'</span>, []):</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> game.get(<span class="st">'gameState'</span>) <span class="kw">in</span> (<span class="st">'OFF'</span>, <span class="st">'FINAL'</span>):</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>                game_ids.append(game[<span class="st">'id'</span>])</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> max_games:</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        game_ids <span class="op">=</span> game_ids[:max_games]</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Found </span><span class="sc">{</span><span class="bu">len</span>(game_ids)<span class="sc">}</span><span class="ss"> completed games for season </span><span class="sc">{</span>season<span class="sc">}</span><span class="ss">.'</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> game_ids</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>game_ids <span class="op">=</span> get_game_ids(SEASON, GAME_TYPE, MAX_GAMES)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The run described here parsed <strong>786 penalty windows across 100 games</strong> — a solid sample for early-season analysis. Full-season results will naturally be more stable as sample sizes grow in each bucket.</p>
<hr>
</section>
<section id="results-score-state-is-not-uniform" class="level2">
<h2 class="anchored" data-anchor-id="results-score-state-is-not-uniform">Results: Score State Is Not Uniform</h2>
<p>This is the empirical foundation of the entire framework. Before looking at team rankings, we need to verify that the score-state buckets actually produce different conversion rates — otherwise stratification adds no value.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="str_buckets.png" class="img-fluid figure-img" alt="Bar chart showing league-average power play goals per 60 minutes broken down by score state bucket"></p>
<figcaption>League-Average PP Goals/60 by Score State, 2024-25 (100-game sample)</figcaption>
</figure>
</div>
<p>The chart above shows league-average PP Goals/60 for each of the five score-state buckets across the 100-game sample. The variation is striking. Teams on the power play while <strong>Chasing</strong> (down 2 or more goals) convert at 10.51 goals per 60 minutes — nearly 70% higher than the Neutral rate of 6.79. The <strong>Leading</strong> bucket comes in at 8.52, while <strong>Protecting</strong> drops to 6.22.</p>
<p>This is the core empirical case for stratification. PP% sees none of this. A team that runs a lot of power plays while chasing will look better in PP% than a team that runs the same number while protecting leads, even if the underlying skill level is identical. The context is doing work that PP% attributes to the team.</p>
<p>The variation also makes intuitive sense. When a team is chasing, the penalty kill unit is under pressure — the opposition is desperate, generating more shots and more urgency. When a team is protecting a big lead, both teams often play more conservatively. These are genuinely different situations and the data confirms it.</p>
<hr>
</section>
<section id="results-the-str-rankings" class="level2">
<h2 class="anchored" data-anchor-id="results-the-str-rankings">Results: The STR Rankings</h2>
<p>With per-60 rates computed and z-scored across the league, the composite STR ranks all 32 teams. Here are the full results from the 2024-25 sample:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="str_rankings.png" class="img-fluid figure-img" alt="Horizontal bar chart showing composite STR rankings for top 15 NHL teams"></p>
<figcaption>STR Rankings — Top 15 Teams, 2024-25 Season (100-game sample)</figcaption>
</figure>
</div>
<p>The chart shows the top 15 teams by composite STR. The x-axis is in z-score weighted units — a value of 1.0 means one standard deviation above the league mean in combined special teams performance.</p>
<p><strong>Winnipeg (WPG)</strong> leads the league at 1.283, and it is not particularly close. Their STR score reflects a power play running at 19.33 goals per 60 minutes combined across all score states, paired with a penalty kill conceding only 5.62 goals per 60. Both numbers rank among the best in the league.</p>
<p><strong>Ottawa (OTT)</strong> ranks second at 1.098. Their PP rate of 19.24 goals per 60 is comparable to Winnipeg, but their shot attempt volume on the power play is actually higher (81.38 attempts per 60 versus Winnipeg’s 65.74), suggesting a more process-driven approach that generates chances at a high rate.</p>
<p><strong>Vancouver (VAN)</strong> rounds out the top three at 0.674, with a strong PK (4.98 goals against per 60) carrying much of their rating.</p>
<p>At the bottom of the rankings, <strong>Edmonton (EDM)</strong> sits last at -1.241, driven primarily by a penalty kill conceding 14.39 goals per 60 minutes — the worst mark in the league in this sample. This is notable given Edmonton’s reputation as an offensive powerhouse; their power play is functional but their PK is dragging the composite rating down significantly.</p>
<p><strong>Buffalo (BUF)</strong> at -0.979 and <strong>Seattle (SEA)</strong> at -0.913 round out the bottom three, both suffering from poor PK performance in the sample.</p>
<p>The full rankings table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rank</th>
<th>Team</th>
<th>PP Goals/60</th>
<th>PP Attempts/60</th>
<th>PK GA/60</th>
<th>STR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>WPG</td>
<td>19.33</td>
<td>65.74</td>
<td>5.62</td>
<td>1.283</td>
</tr>
<tr class="even">
<td>2</td>
<td>OTT</td>
<td>19.24</td>
<td>81.38</td>
<td>7.81</td>
<td>1.098</td>
</tr>
<tr class="odd">
<td>3</td>
<td>VAN</td>
<td>12.41</td>
<td>69.52</td>
<td>4.98</td>
<td>0.674</td>
</tr>
<tr class="even">
<td>4</td>
<td>NJD</td>
<td>8.54</td>
<td>99.88</td>
<td>4.33</td>
<td>0.605</td>
</tr>
<tr class="odd">
<td>5</td>
<td>DAL</td>
<td>2.91</td>
<td>85.92</td>
<td>1.35</td>
<td>0.563</td>
</tr>
<tr class="even">
<td>6</td>
<td>UTA</td>
<td>9.88</td>
<td>74.66</td>
<td>4.54</td>
<td>0.560</td>
</tr>
<tr class="odd">
<td>7</td>
<td>MIN</td>
<td>14.13</td>
<td>90.81</td>
<td>8.90</td>
<td>0.555</td>
</tr>
<tr class="even">
<td>8</td>
<td>FLA</td>
<td>9.27</td>
<td>71.84</td>
<td>4.74</td>
<td>0.461</td>
</tr>
<tr class="odd">
<td>9</td>
<td>MTL</td>
<td>6.11</td>
<td>54.95</td>
<td>3.48</td>
<td>0.349</td>
</tr>
<tr class="even">
<td>10</td>
<td>NSH</td>
<td>6.53</td>
<td>130.55</td>
<td>5.48</td>
<td>0.310</td>
</tr>
<tr class="odd">
<td>11</td>
<td>CGY</td>
<td>14.67</td>
<td>60.15</td>
<td>9.32</td>
<td>0.265</td>
</tr>
<tr class="even">
<td>12</td>
<td>VGK</td>
<td>11.06</td>
<td>108.42</td>
<td>10.70</td>
<td>0.175</td>
</tr>
<tr class="odd">
<td>13</td>
<td>PIT</td>
<td>9.46</td>
<td>97.30</td>
<td>8.76</td>
<td>0.166</td>
</tr>
<tr class="even">
<td>14</td>
<td>CAR</td>
<td>7.41</td>
<td>79.01</td>
<td>6.20</td>
<td>0.154</td>
</tr>
<tr class="odd">
<td>15</td>
<td>NYR</td>
<td>6.53</td>
<td>88.18</td>
<td>6.05</td>
<td>0.024</td>
</tr>
<tr class="even">
<td>16</td>
<td>TOR</td>
<td>3.44</td>
<td>79.18</td>
<td>4.96</td>
<td>0.005</td>
</tr>
<tr class="odd">
<td>17</td>
<td>CHI</td>
<td>10.88</td>
<td>89.73</td>
<td>10.77</td>
<td>-0.000</td>
</tr>
<tr class="even">
<td>18</td>
<td>COL</td>
<td>13.78</td>
<td>63.91</td>
<td>12.05</td>
<td>-0.075</td>
</tr>
<tr class="odd">
<td>19</td>
<td>PHI</td>
<td>7.75</td>
<td>62.00</td>
<td>6.95</td>
<td>-0.118</td>
</tr>
<tr class="even">
<td>20</td>
<td>WSH</td>
<td>3.89</td>
<td>71.27</td>
<td>5.55</td>
<td>-0.226</td>
</tr>
<tr class="odd">
<td>21</td>
<td>CBJ</td>
<td>6.40</td>
<td>91.20</td>
<td>8.35</td>
<td>-0.242</td>
</tr>
<tr class="even">
<td>22</td>
<td>SJS</td>
<td>6.05</td>
<td>102.90</td>
<td>8.91</td>
<td>-0.248</td>
</tr>
<tr class="odd">
<td>23</td>
<td>LAK</td>
<td>8.08</td>
<td>76.18</td>
<td>9.52</td>
<td>-0.277</td>
</tr>
<tr class="even">
<td>24</td>
<td>DET</td>
<td>5.45</td>
<td>95.35</td>
<td>9.88</td>
<td>-0.351</td>
</tr>
<tr class="odd">
<td>25</td>
<td>ANA</td>
<td>0.00</td>
<td>84.00</td>
<td>6.81</td>
<td>-0.429</td>
</tr>
<tr class="even">
<td>26</td>
<td>STL</td>
<td>5.60</td>
<td>60.16</td>
<td>6.85</td>
<td>-0.474</td>
</tr>
<tr class="odd">
<td>27</td>
<td>TBL</td>
<td>6.98</td>
<td>109.30</td>
<td>12.22</td>
<td>-0.545</td>
</tr>
<tr class="even">
<td>28</td>
<td>BOS</td>
<td>4.34</td>
<td>69.47</td>
<td>9.88</td>
<td>-0.562</td>
</tr>
<tr class="odd">
<td>29</td>
<td>NYI</td>
<td>4.66</td>
<td>96.21</td>
<td>10.14</td>
<td>-0.567</td>
</tr>
<tr class="even">
<td>30</td>
<td>SEA</td>
<td>6.28</td>
<td>68.04</td>
<td>13.92</td>
<td>-0.913</td>
</tr>
<tr class="odd">
<td>31</td>
<td>BUF</td>
<td>0.00</td>
<td>93.85</td>
<td>10.01</td>
<td>-0.979</td>
</tr>
<tr class="even">
<td>32</td>
<td>EDM</td>
<td>3.07</td>
<td>78.23</td>
<td>14.39</td>
<td>-1.241</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="results-pp-vs-pk-efficiency" class="level2">
<h2 class="anchored" data-anchor-id="results-pp-vs-pk-efficiency">Results: PP vs PK Efficiency</h2>
<p>The scatter plot below separates PP and PK contributions, making it possible to see which teams are elite at one, both, or neither.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="str_scatter.png" class="img-fluid figure-img" alt="Scatter plot of PP goals per 60 vs PK goals against per 60 with quadrant lines at league means"></p>
<figcaption>PP Efficiency vs PK Efficiency — All Score States, 2024-25</figcaption>
</figure>
</div>
<p>Each dot is a team. The x-axis shows PP Goals/60 (higher is better) and the y-axis shows PK Goals Against/60 (lower is better). The dashed lines sit at the league mean for each axis, dividing the chart into four quadrants. Teams in the lower-right are above average at both — elite special teams overall. Teams in the upper-left are below average at both.</p>
<p>A few things stand out immediately.</p>
<p><strong>Dallas (DAL)</strong> sits alone in the lower-left quadrant — an unusual position. Their PP Goals/60 is just 2.91, ranking near the bottom of the league, but their PK Goals Against/60 is only 1.35, the best penalty kill in this sample by a significant margin. This is a team being carried entirely by their PK, and PP% would never surface this cleanly.</p>
<p><strong>New Jersey (NJD)</strong> is an interesting case near the league mean on both axes but with an exceptionally high PP Attempts/60 of 99.88. Their power play generates volume but hasn’t converted it into goals in this sample — a process-outcome gap worth watching as the season continues.</p>
<p><strong>Edmonton (EDM)</strong> appears in the upper-left — their PK giving up 14.39 goals per 60 is the clear outlier at the top of the chart, confirming what the rankings table showed.</p>
<p><strong>Winnipeg (WPG)</strong> and <strong>Ottawa (OTT)</strong> both sit in the lower-right quadrant, confirming their top-two composite rankings. They are genuinely good at both sides of special teams, not just one.</p>
<hr>
</section>
<section id="deep-dive-winnipeg-jets" class="level2">
<h2 class="anchored" data-anchor-id="deep-dive-winnipeg-jets">Deep Dive: Winnipeg Jets</h2>
<p>As the top-ranked team by STR, the Jets are worth examining by score state in detail.</p>
<p>The left panel shows PP Goals/60 by score state bucket. The Jets’ leading bucket stands out at 42.86 goals per 60 — an exceptional rate, though in a small sample (only 3 minutes of PP time while leading by one). Their Protecting bucket is also strong at 20.74 goals per 60 across 14 minutes of ice time, which is a more meaningful sample. Their Trailing and Neutral power play rates are solid but not exceptional.</p>
<p>The right panel shows PK Goals Against/60. The Jets concede at 10.91 goals per 60 while Chasing — their worst bucket — but hold to 6.09 in the Neutral bucket and a perfect 0.00 in both Trailing and Leading situations. The Protecting bucket shows no data (NaN), meaning they had no power plays to kill while protecting a big lead in this sample.</p>
<p>What the Jets’ profile shows is a team that is particularly dangerous on the power play when they have a lead, and disciplined on the PK in the most common game situations (Neutral, Trailing, Leading). This is a different story than PP% tells.</p>
<hr>
</section>
<section id="limitations-and-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-next-steps">Limitations and Next Steps</h2>
<p>No framework is complete on first pass. A few honest caveats:</p>
<p><strong>The z-score weights are somewhat arbitrary.</strong> The 40/10/40/10 split reflects a reasonable prior — outcomes dominate process — but it hasn’t been validated against long-run predictive accuracy. A natural extension is to fit these weights against future season performance and see what the data prefers.</p>
<p><strong>5v3 situations are included and probably shouldn’t be.</strong> A two-man advantage is a fundamentally different situation from a standard power play. The current implementation doesn’t distinguish between them. Filtering or separately modeling 5v3 windows would improve signal quality.</p>
<p><strong>Score state is set at penalty call time, not dynamically.</strong> A power play that starts at 0-0 but crosses into a lead-change mid-window is still classified in the original bucket. Dynamic re-bucketing mid-window would be more accurate but considerably more complex.</p>
<p><strong>Sample size at the bucket level is thin.</strong> Particularly for Chasing and Protecting, teams may have relatively few minutes in a single season. The per-60 rates are unbiased but noisy. Bayesian shrinkage toward league mean would be a principled improvement.</p>
<p><strong>This sample covers 100 games.</strong> The full 2024-25 regular season is 1,312 games. Rankings will stabilize considerably with the full dataset and some of the more extreme per-60 values (like the Jets’ 42.86 in the Leading bucket) will regress toward true rates.</p>
<hr>
</section>
<section id="full-code" class="level2">
<h2 class="anchored" data-anchor-id="full-code">Full Code</h2>
<p>The complete notebook — including all data fetching, parsing, aggregation, STR computation, and visualization — is available in the repo:</p>
<p>👉 <a href="https://github.com/corsi-isnt-enough/nhl-analytics">github.com/corsi-isnt-enough/nhl-analytics</a></p>
<p>The notebook is written for Python 3.8+ compatibility and has no dependencies beyond the standard scientific stack (pandas, numpy, matplotlib, requests, tqdm).</p>



<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Special Teams Rating: A Better Framework"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2025-06-04</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Buddy Galletti"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [special-teams, methodology, power-play, penalty-kill]</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "PP% and PK% are the most widely cited special teams metrics in hockey. They are also among the most misleading. Here's a ground-up replacement."</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="an">code-fold:</span><span class="co"> true</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">  enabled: false</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Problem with PP% and PK%</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>Ask anyone to evaluate a team's special teams and the first thing they reach for is PP% and PK%. Power play percentage: goals scored divided by opportunities. Penalty kill percentage: opportunities killed without conceding. Simple, intuitive, universally reported.</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>Also quietly broken.</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>Here's the core issue: **both metrics treat all special teams time as equivalent**, when it clearly isn't. A two-minute power play when you're down three goals in the third period is a completely different situation — in terms of strategy, urgency, and opponent behavior — than a power play when you're protecting a one-goal lead in the second. Teams change how they play. Goaltenders change how they play. The underlying rates of scoring chance generation shift meaningfully across these contexts.</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>When you collapse all of that into a single percentage, you're averaging over a distribution that shouldn't be averaged. You're measuring outcomes, not quality. And you're throwing away some of the most useful signal in the data.</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>There's a second problem: **opportunity count as the denominator is unstable**. A team that takes 10 power plays in a sample scores on 2 of them: 20%. A team that takes 40 power plays scores on 8: also 20%. These are treated as equivalent, but the second estimate is far more reliable. Per-60 metrics, where time-on-ice is the denominator, normalize this properly.</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>This post introduces **Special Teams Rating (STR)** — a framework built from play-by-play data that replaces both problems with something more honest.</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Framework</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>STR has three components that build on each other:</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Per-60 normalization** — replace opportunity counts with time-on-ice as the denominator</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Score-state stratification** — split all special teams events into five game-context buckets</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Composite z-score rating** — combine PP and PK components into a single team ranking</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="fu">### Per-60 Normalization</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>For any team $t$ in any score-state bucket $b$, define:</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>\text{PP Goals/60}_{t,b} = \frac{\text{PP Goals}_{t,b}}{\text{PP TOI}_{t,b}} \times 60</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>\text{PK GA/60}_{t,b} = \frac{\text{PK Goals Against}_{t,b}}{\text{PK TOI}_{t,b}} \times 60</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>Where TOI is measured in minutes from the raw play-by-play. This immediately solves the sample-size distortion: a team with 3 minutes of power play time in a given bucket simply has a noisier estimate, not an artificially inflated or deflated percentage.</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>We also track shot attempt volume as a process quality measure:</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>\text{PP Attempts/60}_{t,b} = \frac{\text{SOG} + \text{Missed} + \text{Blocked}}{\text{PP TOI}_{t,b}} \times 60</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a><span class="fu">### Score-State Stratification</span></span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>Every penalty in the data is classified at the moment it is called. The goal differential from the power play team's perspective determines the bucket:</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>\Delta g = \text{Goals}_{PP\text{ team}} - \text{Goals}_{PK\text{ team}} \quad \text{at time of penalty}</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bucket <span class="pp">|</span> Condition <span class="pp">|</span></span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|-----------|</span></span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Chasing <span class="pp">|</span> $\Delta g \leq -2$ <span class="pp">|</span></span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Trailing <span class="pp">|</span> $\Delta g = -1$ <span class="pp">|</span></span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Neutral <span class="pp">|</span> $\Delta g = 0$ <span class="pp">|</span></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Leading <span class="pp">|</span> $\Delta g = +1$ <span class="pp">|</span></span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Protecting <span class="pp">|</span> $\Delta g \geq +2$ <span class="pp">|</span></span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a><span class="fu">### Composite STR</span></span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>To combine PP and PK performance into a single number, we z-score each component across the league, then apply a weighted sum:</span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>z_x = \frac{x - \bar{x}}{\sigma_x}</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>\text{STR}_t = 0.40 \cdot z_{\text{PP Goals/60}} + 0.10 \cdot z_{\text{PP Attempts/60}} - 0.40 \cdot z_{\text{PK GA/60}} - 0.10 \cdot z_{\text{PK Shots Against/60}}</span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>The weights reflect a deliberate philosophy:</span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Goals/60 (40% each side)** — outcomes are the primary signal</span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Shot attempts/60 (10% each side)** — process quality is a secondary signal; volume matters but doesn't dominate</span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**PK components are inverted** — lower goals against and fewer shots against are better, so the z-scores are negated before weighting</span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a>The result is a league-relative rating where positive values mean above average and negative values mean below average.</span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Data Pipeline</span></span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a>Everything runs off the NHL public API's play-by-play endpoint:</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a><span class="in">GET https://api-web.nhle.com/v1/gamecenter/{game_id}/play-by-play</span></span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a>For each game, we make three passes through the event stream:</span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a>**Pass 1 — Score reconstruction.** Walk every event in chronological order, maintaining a live running score for both teams. This is necessary because the API does not store cumulative score on non-goal events — we have to reconstruct it ourselves.</span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a>**Pass 2 — Penalty window identification.** For each <span class="in">`penalty`</span> event, record the PP team, PK team, start time, nominal duration, and the score state at the moment the penalty was called (from Pass 1's running tally).</span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a>**Pass 3 — Event tagging.** For each penalty window, collect all shot-type events (<span class="in">`shot-on-goal`</span>, <span class="in">`goal`</span>, <span class="in">`missed-shot`</span>, <span class="in">`blocked-shot`</span>) that fall within the window's time range, attributed to the correct team. One important detail: a power play goal ends a minor penalty early, so we detect that and clip the window's actual end time accordingly.</span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: dependencies</span></span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm.notebook <span class="im">import</span> tqdm</span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.ticker <span class="im">as</span> mticker</span>
<span id="cb5-126"><a href="#cb5-126" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb5-127"><a href="#cb5-127" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb5-128"><a href="#cb5-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-129"><a href="#cb5-129" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.max_columns'</span>, <span class="va">None</span>)</span>
<span id="cb5-130"><a href="#cb5-130" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.float_format'</span>, <span class="st">'</span><span class="sc">{:.3f}</span><span class="st">'</span>.<span class="bu">format</span>)</span>
<span id="cb5-131"><a href="#cb5-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-132"><a href="#cb5-132" aria-hidden="true" tabindex="-1"></a>BASE_URL <span class="op">=</span> <span class="st">'https://api-web.nhle.com/v1'</span></span>
<span id="cb5-133"><a href="#cb5-133" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Libraries loaded.'</span>)</span>
<span id="cb5-134"><a href="#cb5-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-135"><a href="#cb5-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-138"><a href="#cb5-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb5-139"><a href="#cb5-139" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb5-140"><a href="#cb5-140" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb5-141"><a href="#cb5-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: config</span></span>
<span id="cb5-142"><a href="#cb5-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-143"><a href="#cb5-143" aria-hidden="true" tabindex="-1"></a>SEASON        <span class="op">=</span> <span class="st">'20242025'</span></span>
<span id="cb5-144"><a href="#cb5-144" aria-hidden="true" tabindex="-1"></a>GAME_TYPE     <span class="op">=</span> <span class="dv">2</span>          <span class="co"># 2 = regular season, 3 = playoffs</span></span>
<span id="cb5-145"><a href="#cb5-145" aria-hidden="true" tabindex="-1"></a>MAX_GAMES     <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb5-146"><a href="#cb5-146" aria-hidden="true" tabindex="-1"></a>SLEEP_BETWEEN_REQUESTS <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb5-147"><a href="#cb5-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-148"><a href="#cb5-148" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score_state_bucket(goal_diff: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb5-149"><a href="#cb5-149" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>   goal_diff <span class="op">&lt;=</span>  <span class="op">-</span><span class="dv">2</span>: <span class="cf">return</span> <span class="st">'Chasing'</span></span>
<span id="cb5-150"><a href="#cb5-150" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> goal_diff <span class="op">==</span>  <span class="op">-</span><span class="dv">1</span>: <span class="cf">return</span> <span class="st">'Trailing'</span></span>
<span id="cb5-151"><a href="#cb5-151" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> goal_diff <span class="op">==</span>   <span class="dv">0</span>: <span class="cf">return</span> <span class="st">'Neutral'</span></span>
<span id="cb5-152"><a href="#cb5-152" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> goal_diff <span class="op">==</span>   <span class="dv">1</span>: <span class="cf">return</span> <span class="st">'Leading'</span></span>
<span id="cb5-153"><a href="#cb5-153" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:                  <span class="cf">return</span> <span class="st">'Protecting'</span></span>
<span id="cb5-154"><a href="#cb5-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-155"><a href="#cb5-155" aria-hidden="true" tabindex="-1"></a>BUCKET_ORDER <span class="op">=</span> [<span class="st">'Chasing'</span>, <span class="st">'Trailing'</span>, <span class="st">'Neutral'</span>, <span class="st">'Leading'</span>, <span class="st">'Protecting'</span>]</span>
<span id="cb5-156"><a href="#cb5-156" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Config: season=</span><span class="sc">{</span>SEASON<span class="sc">}</span><span class="ss">, game_type=</span><span class="sc">{</span>GAME_TYPE<span class="sc">}</span><span class="ss">, max_games=</span><span class="sc">{</span>MAX_GAMES<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-157"><a href="#cb5-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-158"><a href="#cb5-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-161"><a href="#cb5-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb5-162"><a href="#cb5-162" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb5-163"><a href="#cb5-163" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb5-164"><a href="#cb5-164" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fetch-game-ids</span></span>
<span id="cb5-165"><a href="#cb5-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-166"><a href="#cb5-166" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_game_ids(season: <span class="bu">str</span>, game_type: <span class="bu">int</span>, max_games<span class="op">=</span><span class="va">None</span>) <span class="op">-&gt;</span> <span class="bu">list</span>:</span>
<span id="cb5-167"><a href="#cb5-167" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Pull all completed regular-season game IDs via the schedule endpoint."""</span></span>
<span id="cb5-168"><a href="#cb5-168" aria-hidden="true" tabindex="-1"></a>    url <span class="op">=</span> <span class="ss">f'</span><span class="sc">{</span>BASE_URL<span class="sc">}</span><span class="ss">/schedule/season/</span><span class="sc">{</span>season<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>game_type<span class="sc">}</span><span class="ss">'</span></span>
<span id="cb5-169"><a href="#cb5-169" aria-hidden="true" tabindex="-1"></a>    resp <span class="op">=</span> requests.get(url)</span>
<span id="cb5-170"><a href="#cb5-170" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> resp.status_code <span class="op">!=</span> <span class="dv">200</span>:</span>
<span id="cb5-171"><a href="#cb5-171" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'Schedule endpoint returned </span><span class="sc">{</span>resp<span class="sc">.</span>status_code<span class="sc">}</span><span class="ss">, falling back to date-range walk.'</span>)</span>
<span id="cb5-172"><a href="#cb5-172" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> _walk_schedule_by_date(season, game_type, max_games)</span>
<span id="cb5-173"><a href="#cb5-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-174"><a href="#cb5-174" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> resp.json()</span>
<span id="cb5-175"><a href="#cb5-175" aria-hidden="true" tabindex="-1"></a>    game_ids <span class="op">=</span> []</span>
<span id="cb5-176"><a href="#cb5-176" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> week <span class="kw">in</span> data.get(<span class="st">'gameWeek'</span>, []):</span>
<span id="cb5-177"><a href="#cb5-177" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> game <span class="kw">in</span> week.get(<span class="st">'games'</span>, []):</span>
<span id="cb5-178"><a href="#cb5-178" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> game.get(<span class="st">'gameState'</span>) <span class="kw">in</span> (<span class="st">'OFF'</span>, <span class="st">'FINAL'</span>):</span>
<span id="cb5-179"><a href="#cb5-179" aria-hidden="true" tabindex="-1"></a>                game_ids.append(game[<span class="st">'id'</span>])</span>
<span id="cb5-180"><a href="#cb5-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-181"><a href="#cb5-181" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> max_games:</span>
<span id="cb5-182"><a href="#cb5-182" aria-hidden="true" tabindex="-1"></a>        game_ids <span class="op">=</span> game_ids[:max_games]</span>
<span id="cb5-183"><a href="#cb5-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-184"><a href="#cb5-184" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Found </span><span class="sc">{</span><span class="bu">len</span>(game_ids)<span class="sc">}</span><span class="ss"> completed games for season </span><span class="sc">{</span>season<span class="sc">}</span><span class="ss">.'</span>)</span>
<span id="cb5-185"><a href="#cb5-185" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> game_ids</span>
<span id="cb5-186"><a href="#cb5-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-187"><a href="#cb5-187" aria-hidden="true" tabindex="-1"></a>game_ids <span class="op">=</span> get_game_ids(SEASON, GAME_TYPE, MAX_GAMES)</span>
<span id="cb5-188"><a href="#cb5-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-189"><a href="#cb5-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-190"><a href="#cb5-190" aria-hidden="true" tabindex="-1"></a>The run described here parsed **786 penalty windows across 100 games** — a solid sample for early-season analysis. Full-season results will naturally be more stable as sample sizes grow in each bucket.</span>
<span id="cb5-191"><a href="#cb5-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-192"><a href="#cb5-192" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-193"><a href="#cb5-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-194"><a href="#cb5-194" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results: Score State Is Not Uniform</span></span>
<span id="cb5-195"><a href="#cb5-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-196"><a href="#cb5-196" aria-hidden="true" tabindex="-1"></a>This is the empirical foundation of the entire framework. Before looking at team rankings, we need to verify that the score-state buckets actually produce different conversion rates — otherwise stratification adds no value.</span>
<span id="cb5-197"><a href="#cb5-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-198"><a href="#cb5-198" aria-hidden="true" tabindex="-1"></a><span class="al">![League-Average PP Goals/60 by Score State, 2024-25 (100-game sample)](str_buckets.png)</span>{fig-alt="Bar chart showing league-average power play goals per 60 minutes broken down by score state bucket"}</span>
<span id="cb5-199"><a href="#cb5-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-200"><a href="#cb5-200" aria-hidden="true" tabindex="-1"></a>The chart above shows league-average PP Goals/60 for each of the five score-state buckets across the 100-game sample. The variation is striking. Teams on the power play while **Chasing** (down 2 or more goals) convert at 10.51 goals per 60 minutes — nearly 70% higher than the Neutral rate of 6.79. The **Leading** bucket comes in at 8.52, while **Protecting** drops to 6.22.</span>
<span id="cb5-201"><a href="#cb5-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-202"><a href="#cb5-202" aria-hidden="true" tabindex="-1"></a>This is the core empirical case for stratification. PP% sees none of this. A team that runs a lot of power plays while chasing will look better in PP% than a team that runs the same number while protecting leads, even if the underlying skill level is identical. The context is doing work that PP% attributes to the team.</span>
<span id="cb5-203"><a href="#cb5-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-204"><a href="#cb5-204" aria-hidden="true" tabindex="-1"></a>The variation also makes intuitive sense. When a team is chasing, the penalty kill unit is under pressure — the opposition is desperate, generating more shots and more urgency. When a team is protecting a big lead, both teams often play more conservatively. These are genuinely different situations and the data confirms it.</span>
<span id="cb5-205"><a href="#cb5-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-206"><a href="#cb5-206" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-207"><a href="#cb5-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-208"><a href="#cb5-208" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results: The STR Rankings</span></span>
<span id="cb5-209"><a href="#cb5-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-210"><a href="#cb5-210" aria-hidden="true" tabindex="-1"></a>With per-60 rates computed and z-scored across the league, the composite STR ranks all 32 teams. Here are the full results from the 2024-25 sample:</span>
<span id="cb5-211"><a href="#cb5-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-212"><a href="#cb5-212" aria-hidden="true" tabindex="-1"></a><span class="al">![STR Rankings — Top 15 Teams, 2024-25 Season (100-game sample)](str_rankings.png)</span>{fig-alt="Horizontal bar chart showing composite STR rankings for top 15 NHL teams"}</span>
<span id="cb5-213"><a href="#cb5-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-214"><a href="#cb5-214" aria-hidden="true" tabindex="-1"></a>The chart shows the top 15 teams by composite STR. The x-axis is in z-score weighted units — a value of 1.0 means one standard deviation above the league mean in combined special teams performance.</span>
<span id="cb5-215"><a href="#cb5-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-216"><a href="#cb5-216" aria-hidden="true" tabindex="-1"></a>**Winnipeg (WPG)** leads the league at 1.283, and it is not particularly close. Their STR score reflects a power play running at 19.33 goals per 60 minutes combined across all score states, paired with a penalty kill conceding only 5.62 goals per 60. Both numbers rank among the best in the league.</span>
<span id="cb5-217"><a href="#cb5-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-218"><a href="#cb5-218" aria-hidden="true" tabindex="-1"></a>**Ottawa (OTT)** ranks second at 1.098. Their PP rate of 19.24 goals per 60 is comparable to Winnipeg, but their shot attempt volume on the power play is actually higher (81.38 attempts per 60 versus Winnipeg's 65.74), suggesting a more process-driven approach that generates chances at a high rate.</span>
<span id="cb5-219"><a href="#cb5-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-220"><a href="#cb5-220" aria-hidden="true" tabindex="-1"></a>**Vancouver (VAN)** rounds out the top three at 0.674, with a strong PK (4.98 goals against per 60) carrying much of their rating.</span>
<span id="cb5-221"><a href="#cb5-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-222"><a href="#cb5-222" aria-hidden="true" tabindex="-1"></a>At the bottom of the rankings, **Edmonton (EDM)** sits last at -1.241, driven primarily by a penalty kill conceding 14.39 goals per 60 minutes — the worst mark in the league in this sample. This is notable given Edmonton's reputation as an offensive powerhouse; their power play is functional but their PK is dragging the composite rating down significantly.</span>
<span id="cb5-223"><a href="#cb5-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-224"><a href="#cb5-224" aria-hidden="true" tabindex="-1"></a>**Buffalo (BUF)** at -0.979 and **Seattle (SEA)** at -0.913 round out the bottom three, both suffering from poor PK performance in the sample.</span>
<span id="cb5-225"><a href="#cb5-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-226"><a href="#cb5-226" aria-hidden="true" tabindex="-1"></a>The full rankings table:</span>
<span id="cb5-227"><a href="#cb5-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-228"><a href="#cb5-228" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rank <span class="pp">|</span> Team <span class="pp">|</span> PP Goals/60 <span class="pp">|</span> PP Attempts/60 <span class="pp">|</span> PK GA/60 <span class="pp">|</span> STR <span class="pp">|</span></span>
<span id="cb5-229"><a href="#cb5-229" aria-hidden="true" tabindex="-1"></a><span class="pp">|------|------|-------------|----------------|----------|-----|</span></span>
<span id="cb5-230"><a href="#cb5-230" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> WPG <span class="pp">|</span> 19.33 <span class="pp">|</span> 65.74 <span class="pp">|</span> 5.62 <span class="pp">|</span> 1.283 <span class="pp">|</span></span>
<span id="cb5-231"><a href="#cb5-231" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> OTT <span class="pp">|</span> 19.24 <span class="pp">|</span> 81.38 <span class="pp">|</span> 7.81 <span class="pp">|</span> 1.098 <span class="pp">|</span></span>
<span id="cb5-232"><a href="#cb5-232" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> VAN <span class="pp">|</span> 12.41 <span class="pp">|</span> 69.52 <span class="pp">|</span> 4.98 <span class="pp">|</span> 0.674 <span class="pp">|</span></span>
<span id="cb5-233"><a href="#cb5-233" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> NJD <span class="pp">|</span> 8.54 <span class="pp">|</span> 99.88 <span class="pp">|</span> 4.33 <span class="pp">|</span> 0.605 <span class="pp">|</span></span>
<span id="cb5-234"><a href="#cb5-234" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> DAL <span class="pp">|</span> 2.91 <span class="pp">|</span> 85.92 <span class="pp">|</span> 1.35 <span class="pp">|</span> 0.563 <span class="pp">|</span></span>
<span id="cb5-235"><a href="#cb5-235" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> UTA <span class="pp">|</span> 9.88 <span class="pp">|</span> 74.66 <span class="pp">|</span> 4.54 <span class="pp">|</span> 0.560 <span class="pp">|</span></span>
<span id="cb5-236"><a href="#cb5-236" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 7 <span class="pp">|</span> MIN <span class="pp">|</span> 14.13 <span class="pp">|</span> 90.81 <span class="pp">|</span> 8.90 <span class="pp">|</span> 0.555 <span class="pp">|</span></span>
<span id="cb5-237"><a href="#cb5-237" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 8 <span class="pp">|</span> FLA <span class="pp">|</span> 9.27 <span class="pp">|</span> 71.84 <span class="pp">|</span> 4.74 <span class="pp">|</span> 0.461 <span class="pp">|</span></span>
<span id="cb5-238"><a href="#cb5-238" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 9 <span class="pp">|</span> MTL <span class="pp">|</span> 6.11 <span class="pp">|</span> 54.95 <span class="pp">|</span> 3.48 <span class="pp">|</span> 0.349 <span class="pp">|</span></span>
<span id="cb5-239"><a href="#cb5-239" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 10 <span class="pp">|</span> NSH <span class="pp">|</span> 6.53 <span class="pp">|</span> 130.55 <span class="pp">|</span> 5.48 <span class="pp">|</span> 0.310 <span class="pp">|</span></span>
<span id="cb5-240"><a href="#cb5-240" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 11 <span class="pp">|</span> CGY <span class="pp">|</span> 14.67 <span class="pp">|</span> 60.15 <span class="pp">|</span> 9.32 <span class="pp">|</span> 0.265 <span class="pp">|</span></span>
<span id="cb5-241"><a href="#cb5-241" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 12 <span class="pp">|</span> VGK <span class="pp">|</span> 11.06 <span class="pp">|</span> 108.42 <span class="pp">|</span> 10.70 <span class="pp">|</span> 0.175 <span class="pp">|</span></span>
<span id="cb5-242"><a href="#cb5-242" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 13 <span class="pp">|</span> PIT <span class="pp">|</span> 9.46 <span class="pp">|</span> 97.30 <span class="pp">|</span> 8.76 <span class="pp">|</span> 0.166 <span class="pp">|</span></span>
<span id="cb5-243"><a href="#cb5-243" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 14 <span class="pp">|</span> CAR <span class="pp">|</span> 7.41 <span class="pp">|</span> 79.01 <span class="pp">|</span> 6.20 <span class="pp">|</span> 0.154 <span class="pp">|</span></span>
<span id="cb5-244"><a href="#cb5-244" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 15 <span class="pp">|</span> NYR <span class="pp">|</span> 6.53 <span class="pp">|</span> 88.18 <span class="pp">|</span> 6.05 <span class="pp">|</span> 0.024 <span class="pp">|</span></span>
<span id="cb5-245"><a href="#cb5-245" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 16 <span class="pp">|</span> TOR <span class="pp">|</span> 3.44 <span class="pp">|</span> 79.18 <span class="pp">|</span> 4.96 <span class="pp">|</span> 0.005 <span class="pp">|</span></span>
<span id="cb5-246"><a href="#cb5-246" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 17 <span class="pp">|</span> CHI <span class="pp">|</span> 10.88 <span class="pp">|</span> 89.73 <span class="pp">|</span> 10.77 <span class="pp">|</span> -0.000 <span class="pp">|</span></span>
<span id="cb5-247"><a href="#cb5-247" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 18 <span class="pp">|</span> COL <span class="pp">|</span> 13.78 <span class="pp">|</span> 63.91 <span class="pp">|</span> 12.05 <span class="pp">|</span> -0.075 <span class="pp">|</span></span>
<span id="cb5-248"><a href="#cb5-248" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 19 <span class="pp">|</span> PHI <span class="pp">|</span> 7.75 <span class="pp">|</span> 62.00 <span class="pp">|</span> 6.95 <span class="pp">|</span> -0.118 <span class="pp">|</span></span>
<span id="cb5-249"><a href="#cb5-249" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 20 <span class="pp">|</span> WSH <span class="pp">|</span> 3.89 <span class="pp">|</span> 71.27 <span class="pp">|</span> 5.55 <span class="pp">|</span> -0.226 <span class="pp">|</span></span>
<span id="cb5-250"><a href="#cb5-250" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 21 <span class="pp">|</span> CBJ <span class="pp">|</span> 6.40 <span class="pp">|</span> 91.20 <span class="pp">|</span> 8.35 <span class="pp">|</span> -0.242 <span class="pp">|</span></span>
<span id="cb5-251"><a href="#cb5-251" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 22 <span class="pp">|</span> SJS <span class="pp">|</span> 6.05 <span class="pp">|</span> 102.90 <span class="pp">|</span> 8.91 <span class="pp">|</span> -0.248 <span class="pp">|</span></span>
<span id="cb5-252"><a href="#cb5-252" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 23 <span class="pp">|</span> LAK <span class="pp">|</span> 8.08 <span class="pp">|</span> 76.18 <span class="pp">|</span> 9.52 <span class="pp">|</span> -0.277 <span class="pp">|</span></span>
<span id="cb5-253"><a href="#cb5-253" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 24 <span class="pp">|</span> DET <span class="pp">|</span> 5.45 <span class="pp">|</span> 95.35 <span class="pp">|</span> 9.88 <span class="pp">|</span> -0.351 <span class="pp">|</span></span>
<span id="cb5-254"><a href="#cb5-254" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 25 <span class="pp">|</span> ANA <span class="pp">|</span> 0.00 <span class="pp">|</span> 84.00 <span class="pp">|</span> 6.81 <span class="pp">|</span> -0.429 <span class="pp">|</span></span>
<span id="cb5-255"><a href="#cb5-255" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 26 <span class="pp">|</span> STL <span class="pp">|</span> 5.60 <span class="pp">|</span> 60.16 <span class="pp">|</span> 6.85 <span class="pp">|</span> -0.474 <span class="pp">|</span></span>
<span id="cb5-256"><a href="#cb5-256" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 27 <span class="pp">|</span> TBL <span class="pp">|</span> 6.98 <span class="pp">|</span> 109.30 <span class="pp">|</span> 12.22 <span class="pp">|</span> -0.545 <span class="pp">|</span></span>
<span id="cb5-257"><a href="#cb5-257" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 28 <span class="pp">|</span> BOS <span class="pp">|</span> 4.34 <span class="pp">|</span> 69.47 <span class="pp">|</span> 9.88 <span class="pp">|</span> -0.562 <span class="pp">|</span></span>
<span id="cb5-258"><a href="#cb5-258" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 29 <span class="pp">|</span> NYI <span class="pp">|</span> 4.66 <span class="pp">|</span> 96.21 <span class="pp">|</span> 10.14 <span class="pp">|</span> -0.567 <span class="pp">|</span></span>
<span id="cb5-259"><a href="#cb5-259" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 30 <span class="pp">|</span> SEA <span class="pp">|</span> 6.28 <span class="pp">|</span> 68.04 <span class="pp">|</span> 13.92 <span class="pp">|</span> -0.913 <span class="pp">|</span></span>
<span id="cb5-260"><a href="#cb5-260" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 31 <span class="pp">|</span> BUF <span class="pp">|</span> 0.00 <span class="pp">|</span> 93.85 <span class="pp">|</span> 10.01 <span class="pp">|</span> -0.979 <span class="pp">|</span></span>
<span id="cb5-261"><a href="#cb5-261" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 32 <span class="pp">|</span> EDM <span class="pp">|</span> 3.07 <span class="pp">|</span> 78.23 <span class="pp">|</span> 14.39 <span class="pp">|</span> -1.241 <span class="pp">|</span></span>
<span id="cb5-262"><a href="#cb5-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-263"><a href="#cb5-263" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-264"><a href="#cb5-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-265"><a href="#cb5-265" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results: PP vs PK Efficiency</span></span>
<span id="cb5-266"><a href="#cb5-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-267"><a href="#cb5-267" aria-hidden="true" tabindex="-1"></a>The scatter plot below separates PP and PK contributions, making it possible to see which teams are elite at one, both, or neither.</span>
<span id="cb5-268"><a href="#cb5-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-269"><a href="#cb5-269" aria-hidden="true" tabindex="-1"></a><span class="al">![PP Efficiency vs PK Efficiency — All Score States, 2024-25](str_scatter.png)</span>{fig-alt="Scatter plot of PP goals per 60 vs PK goals against per 60 with quadrant lines at league means"}</span>
<span id="cb5-270"><a href="#cb5-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-271"><a href="#cb5-271" aria-hidden="true" tabindex="-1"></a>Each dot is a team. The x-axis shows PP Goals/60 (higher is better) and the y-axis shows PK Goals Against/60 (lower is better). The dashed lines sit at the league mean for each axis, dividing the chart into four quadrants. Teams in the lower-right are above average at both — elite special teams overall. Teams in the upper-left are below average at both.</span>
<span id="cb5-272"><a href="#cb5-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-273"><a href="#cb5-273" aria-hidden="true" tabindex="-1"></a>A few things stand out immediately.</span>
<span id="cb5-274"><a href="#cb5-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-275"><a href="#cb5-275" aria-hidden="true" tabindex="-1"></a>**Dallas (DAL)** sits alone in the lower-left quadrant — an unusual position. Their PP Goals/60 is just 2.91, ranking near the bottom of the league, but their PK Goals Against/60 is only 1.35, the best penalty kill in this sample by a significant margin. This is a team being carried entirely by their PK, and PP% would never surface this cleanly.</span>
<span id="cb5-276"><a href="#cb5-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-277"><a href="#cb5-277" aria-hidden="true" tabindex="-1"></a>**New Jersey (NJD)** is an interesting case near the league mean on both axes but with an exceptionally high PP Attempts/60 of 99.88. Their power play generates volume but hasn't converted it into goals in this sample — a process-outcome gap worth watching as the season continues.</span>
<span id="cb5-278"><a href="#cb5-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-279"><a href="#cb5-279" aria-hidden="true" tabindex="-1"></a>**Edmonton (EDM)** appears in the upper-left — their PK giving up 14.39 goals per 60 is the clear outlier at the top of the chart, confirming what the rankings table showed.</span>
<span id="cb5-280"><a href="#cb5-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-281"><a href="#cb5-281" aria-hidden="true" tabindex="-1"></a>**Winnipeg (WPG)** and **Ottawa (OTT)** both sit in the lower-right quadrant, confirming their top-two composite rankings. They are genuinely good at both sides of special teams, not just one.</span>
<span id="cb5-282"><a href="#cb5-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-283"><a href="#cb5-283" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-284"><a href="#cb5-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-285"><a href="#cb5-285" aria-hidden="true" tabindex="-1"></a><span class="fu">## Deep Dive: Winnipeg Jets</span></span>
<span id="cb5-286"><a href="#cb5-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-287"><a href="#cb5-287" aria-hidden="true" tabindex="-1"></a>As the top-ranked team by STR, the Jets are worth examining by score state in detail.</span>
<span id="cb5-288"><a href="#cb5-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-289"><a href="#cb5-289" aria-hidden="true" tabindex="-1"></a>The left panel shows PP Goals/60 by score state bucket. The Jets' leading bucket stands out at 42.86 goals per 60 — an exceptional rate, though in a small sample (only 3 minutes of PP time while leading by one). Their Protecting bucket is also strong at 20.74 goals per 60 across 14 minutes of ice time, which is a more meaningful sample. Their Trailing and Neutral power play rates are solid but not exceptional.</span>
<span id="cb5-290"><a href="#cb5-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-291"><a href="#cb5-291" aria-hidden="true" tabindex="-1"></a>The right panel shows PK Goals Against/60. The Jets concede at 10.91 goals per 60 while Chasing — their worst bucket — but hold to 6.09 in the Neutral bucket and a perfect 0.00 in both Trailing and Leading situations. The Protecting bucket shows no data (NaN), meaning they had no power plays to kill while protecting a big lead in this sample.</span>
<span id="cb5-292"><a href="#cb5-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-293"><a href="#cb5-293" aria-hidden="true" tabindex="-1"></a>What the Jets' profile shows is a team that is particularly dangerous on the power play when they have a lead, and disciplined on the PK in the most common game situations (Neutral, Trailing, Leading). This is a different story than PP% tells.</span>
<span id="cb5-294"><a href="#cb5-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-295"><a href="#cb5-295" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-296"><a href="#cb5-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-297"><a href="#cb5-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations and Next Steps</span></span>
<span id="cb5-298"><a href="#cb5-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-299"><a href="#cb5-299" aria-hidden="true" tabindex="-1"></a>No framework is complete on first pass. A few honest caveats:</span>
<span id="cb5-300"><a href="#cb5-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-301"><a href="#cb5-301" aria-hidden="true" tabindex="-1"></a>**The z-score weights are somewhat arbitrary.** The 40/10/40/10 split reflects a reasonable prior — outcomes dominate process — but it hasn't been validated against long-run predictive accuracy. A natural extension is to fit these weights against future season performance and see what the data prefers.</span>
<span id="cb5-302"><a href="#cb5-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-303"><a href="#cb5-303" aria-hidden="true" tabindex="-1"></a>**5v3 situations are included and probably shouldn't be.** A two-man advantage is a fundamentally different situation from a standard power play. The current implementation doesn't distinguish between them. Filtering or separately modeling 5v3 windows would improve signal quality.</span>
<span id="cb5-304"><a href="#cb5-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-305"><a href="#cb5-305" aria-hidden="true" tabindex="-1"></a>**Score state is set at penalty call time, not dynamically.** A power play that starts at 0-0 but crosses into a lead-change mid-window is still classified in the original bucket. Dynamic re-bucketing mid-window would be more accurate but considerably more complex.</span>
<span id="cb5-306"><a href="#cb5-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-307"><a href="#cb5-307" aria-hidden="true" tabindex="-1"></a>**Sample size at the bucket level is thin.** Particularly for Chasing and Protecting, teams may have relatively few minutes in a single season. The per-60 rates are unbiased but noisy. Bayesian shrinkage toward league mean would be a principled improvement.</span>
<span id="cb5-308"><a href="#cb5-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-309"><a href="#cb5-309" aria-hidden="true" tabindex="-1"></a>**This sample covers 100 games.** The full 2024-25 regular season is 1,312 games. Rankings will stabilize considerably with the full dataset and some of the more extreme per-60 values (like the Jets' 42.86 in the Leading bucket) will regress toward true rates.</span>
<span id="cb5-310"><a href="#cb5-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-311"><a href="#cb5-311" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb5-312"><a href="#cb5-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-313"><a href="#cb5-313" aria-hidden="true" tabindex="-1"></a><span class="fu">## Full Code</span></span>
<span id="cb5-314"><a href="#cb5-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-315"><a href="#cb5-315" aria-hidden="true" tabindex="-1"></a>The complete notebook — including all data fetching, parsing, aggregation, STR computation, and visualization — is available in the repo:</span>
<span id="cb5-316"><a href="#cb5-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-317"><a href="#cb5-317" aria-hidden="true" tabindex="-1"></a>👉 <span class="co">[</span><span class="ot">github.com/corsi-isnt-enough/nhl-analytics</span><span class="co">](https://github.com/corsi-isnt-enough/nhl-analytics)</span></span>
<span id="cb5-318"><a href="#cb5-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-319"><a href="#cb5-319" aria-hidden="true" tabindex="-1"></a>The notebook is written for Python 3.8+ compatibility and has no dependencies beyond the standard scientific stack (pandas, numpy, matplotlib, requests, tqdm).</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>